title: Damián Fanaro
description: Personal Website

url: https://damianfanaro.com
baseurl: ""

markdown: kramdown
highlighter: rouge

navigation:
  - title: Home
    url: /
  - title: About Me
    url: /about
  - title: Contact Me
    url: /contact
  - title: Services
    url: /services

social:
  youtube: damianfanaro
  github: damianfanaro
  twitter: DamianFanaro
  linkedin: damianfanaro
  email: damianfanaro@gmail.com

google_analytics: "UA-67086722-1"
